CREATE TABLE [dbo].[TblGuardians]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_GuardianID] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_TblGuardian_UserID] FOREIGN KEY([ID]) REFERENCES [dbo].[TblUsers]([ID]) ON DELETE CASCADE,
)
