CREATE TABLE [dbo].[TblSecretaries]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_SecretaryID] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_TblSecretary_UserID] FOREIGN KEY([ID]) REFERENCES [dbo].[TblUsers]([ID]) ON DELETE CASCADE,
)
