CREATE TABLE [dbo].[TblStudents]
(
	[ID]			INT			NOT NULL IDENTITY(1,1), 
    [DataOfBirth]	DATETIME	NULL, 
    [GuardianFK]	INT			NULL,
	CONSTRAINT [PK_StudentID] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_TblStudent_UserID]		FOREIGN KEY([ID])			REFERENCES [dbo].[TblUsers]([ID]) ON DELETE CASCADE,
	CONSTRAINT [FK_TblStudent_GuardianID]	FOREIGN KEY([GuardianFK])	REFERENCES [dbo].[TblGuardians]([ID]) ON DELETE CASCADE
)
