CREATE TABLE [dbo].[TblTeachers]
(
	[ID] INT NOT NULL PRIMARY KEY,
	CONSTRAINT [PK_TeacherID] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_TblTeacher_UserID] FOREIGN KEY([ID]) REFERENCES [dbo].[TblUsers]([ID]) ON DELETE CASCADE,
)
