CREATE TABLE [dbo].[TblClasses]
(
	[ID]			INT				NOT NULL IDENTITY(1,1),
	[SchoolYear]	NVARCHAR(MAX)	NULL,
	[Year]			NVARCHAR(MAX)	NULL,
	[ClassDesc]		NVARCHAR(MAX)	NULL,
	[SchoolFK]		INT				NULL,
	[TeacherFK]		INT				NULL,
	CONSTRAINT [PK_CLassID] PRIMARY KEY CLUSTERED ([ID] ASC)
)
