CREATE TABLE [dbo].[TblTimes]
(
	[ID]		INT				NOT NULL IDENTITY(1,1),
	[SchoolFK]	INT				NULL,
    [StartTime]	NVARCHAR(MAX)	NULL,
	[EndTime]	NVARCHAR(MAX)	NULL,
	CONSTRAINT [PK_TimeID] PRIMARY KEY CLUSTERED ([ID] ASC)
)
